// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vika2603/100x-cli/api/futures (interfaces: Doer)
//
// Generated by this command:
//
//	mockgen -destination internal/mocks/futures_doer_mock.go -package mocks github.com/vika2603/100x-cli/api/futures Doer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDoer is a mock of Doer interface.
type MockDoer struct {
	ctrl     *gomock.Controller
	recorder *MockDoerMockRecorder
	isgomock struct{}
}

// MockDoerMockRecorder is the mock recorder for MockDoer.
type MockDoerMockRecorder struct {
	mock *MockDoer
}

// NewMockDoer creates a new mock instance.
func NewMockDoer(ctrl *gomock.Controller) *MockDoer {
	mock := &MockDoer{ctrl: ctrl}
	mock.recorder = &MockDoerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDoer) EXPECT() *MockDoerMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockDoer) Get(ctx context.Context, path string, in, out any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, path, in, out)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockDoerMockRecorder) Get(ctx, path, in, out any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDoer)(nil).Get), ctx, path, in, out)
}

// Post mocks base method.
func (m *MockDoer) Post(ctx context.Context, path string, in, out any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Post", ctx, path, in, out)
	ret0, _ := ret[0].(error)
	return ret0
}

// Post indicates an expected call of Post.
func (mr *MockDoerMockRecorder) Post(ctx, path, in, out any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Post", reflect.TypeOf((*MockDoer)(nil).Post), ctx, path, in, out)
}
